# Generated by Django 2.2 on 2019-12-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191227_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prince',
            new_name='price',
        ),
    ]
