# Generated by Django 2.2.8 on 2020-01-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200111_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refund_grant',
            new_name='refund_granted',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='refund_request',
            new_name='refund_requested',
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
        ),
    ]
